name: Unbreakable
favicon: null
layout_spectrum: 0.5716527260374278
typography_spectrum: 0.9065741682425141
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6221986750606447
  lightness: 0.37808226398192346
  saturation: 0.7194914489518851
  rhythmicContrast: 0.3720759432762861
purpose: []
