name: Unbreakable
favicon: null
layout_spectrum: 0.5716527260374278
typography_spectrum: 0.9065741682425141
title: Media Collective
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#01010a'
    - '#1dabb9'
    - '#1b6379'
    - '#86868a'
  brandStrength: 0.6221986750606447
  lightness: 0.8125
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
